### ISSUE TITLE
Release documentation is not public

### ISSUE THREAD

**Issue by fatso83** [hashicorp/vagrant-vmware-desktop#26] opened 2021-10-27 12:06 UTC
The bottom of the README.md file for this project says 
> See the release documentation in the [Vagrant confluence page](https://hashicorp.atlassian.net/wiki/spaces/vagrant/pages/1039532466/Vagrant+VMware)

and has a link to https://hashicorp.atlassian.net/wiki/spaces/vagrant/pages/1039532466/Vagrant+VMware. That Confluence space is not open to public, demanding authorization, and so it has no place on a public open source project, unless that space is either opened up for public or the docs are moved/copied into some public wiki.

**Comment by chrisroberts** [comment] 2021-10-30 00:21
Duplicate of #21

**Closed by chrisroberts** 2021-10-30 00:21 UTC
